travis: convert to container infrastructure
This uses the new container infrastructure in order to use build caches. The disadvantage is that we require that everything is available from Hackage, and this also can not test building the CUDA backend. However, this will hopefully reduce build times and reduce the chances of the build timing out or running out of memory.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,157 +1,85 @@
-language: haskell
-env:
-  global:
-    - HAPPY=1.19.5
-    - ALEX=3.1.4
+# This file has been generated -- see https://github.com/hvr/multi-ghc-travis
+language: c
+sudo: false
 
-    - SHA_ACCELERATE=11bde8004579b047c5dee97efec61fd05d0b79a1
-    - URL_ACCELERATE=https://github.com/AccelerateHS/accelerate.git
+cache:
+  directories:
+    - $HOME/.cabal-snapshot
+    - $HOME/.cabal/packages
 
-    - SHA_ACCELERATE_IO=2d135c67e5da4a6789c98569cb9685e545471ba0
-    - URL_ACCELERATE_IO=https://github.com/AccelerateHS/accelerate-io.git
-
-    - SHA_ACCELERATE_FFT=3eb505777d2e358cd6bdee0e7d8553d7f8afec41
-    - URL_ACCELERATE_FFT=https://github.com/AccelerateHS/accelerate-fft.git
-
-    - SHA_ACCELERATE_CUDA=0de7835efbaee27eca556c0211afaea71b8e9931
-    - URL_ACCELERATE_CUDA=https://github.com/AccelerateHS/accelerate-cuda.git
-
-    - SHA_GLOSS_ACCELERATE=b57bd2d6fac30e198e9acea9336de6466d02bb4f
-    - URL_GLOSS_ACCELERATE=https://github.com/tmcdonell/gloss-accelerate.git
-
-    - SHA_GLOSS_RASTER_ACCELERATE=e594b80800e4c8bfab5d1f955fa1bdbd13fc2152
-    - URL_GLOSS_RASTER_ACCELERATE=https://github.com/tmcdonell/gloss-raster-accelerate.git
-
-  matrix:
-    - GHC=7.8.4
-    - GHC=7.8.4 CUDA=6.5-14
-    - GHC=7.8.4 CUDA=7.0-28
-    - GHC=7.10.1 CABAL=1.22
-      # GHC-7.10 is too slow and uses too much memory for a complete build
-      # within the 50 minute time limit.
-      # - GHC=7.10.1 CABAL=1.22 CUDA=6.5-14
-      # - GHC=7.10.1 CABAL=1.22 CUDA=7.0-28
-    - GHC=head CABAL=head CUDA=7.0-28
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
 
 matrix:
-    allow_failures:
-        - env: GHC=head CABAL=head CUDA=7.0-28
+  include:
+    - env: CABAL=1.18 GHC=7.8.4
+      compiler: ": #GHC 7.8.4"
+      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
+    - env: CABAL=1.22 GHC=7.10.2
+      compiler: ": #GHC 7.10.2"
+      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2], sources: [hvr-ghc]}}
+    - env: CABAL=head GHC=head
+      compiler: ": #GHC head"
+      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
+
+  allow_failures:
+    - env: CABAL=head GHC=head
 
 before_install:
-    # Fetch accelerate dependencies
-    - echo "Checking out dependencies"
-    - travis_retry git clone -b release/0.15 ${URL_ACCELERATE} deps/accelerate
-    - pushd deps/accelerate
-    - git reset --hard ${SHA_ACCELERATE}
-    - popd
-
-    - travis_retry git clone -b release/0.15 ${URL_ACCELERATE_IO} deps/accelerate-io
-    - pushd deps/accelerate-io
-    - git reset --hard ${SHA_ACCELERATE_IO}
-    - popd
-
-    - travis_retry git clone -b release/0.15 ${URL_ACCELERATE_FFT} deps/accelerate-fft
-    - pushd deps/accelerate-fft
-    - git reset --hard ${SHA_ACCELERATE_FFT}
-    - popd
-
-    - travis_retry git clone -b release/1.9 ${URL_GLOSS_ACCELERATE} deps/gloss-accelerate
-    - pushd deps/gloss-accelerate
-    - git reset --hard ${SHA_GLOSS_ACCELERATE}
-    - popd
-
-    - travis_retry git clone -b release/1.9 ${URL_GLOSS_RASTER_ACCELERATE} deps/gloss-raster-accelerate
-    - pushd deps/gloss-raster-accelerate
-    - git reset --hard ${SHA_GLOSS_RASTER_ACCELERATE}
-    - popd
-
-    - |
-        if [ ${CUDA} ]; then
-            travis_retry git clone -b release/0.15 ${URL_ACCELERATE_CUDA} deps/accelerate-cuda
-            pushd deps/accelerate-cuda
-            git reset --hard ${SHA_ACCELERATE_CUDA}
-            popd
-        fi
-
-    # If travis doesn't have the version of GHC that we want, get it from hvr's PPA
-    - echo "Setting up GHC"
-    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
-    - travis_retry sudo apt-get update -qq
-    - travis_retry sudo apt-get autoremove
-    # - travis_retry sudo apt-get install -y c2hs
-    - travis_retry sudo apt-get install happy-${HAPPY} alex-${ALEX}
-    - export PATH=/opt/alex/${ALEX}/bin:/opt/happy/${HAPPY}/bin:${PATH}
-    - export PATH=/usr/local/ghc/${GHC}/bin:${PATH}
-    - |
-        if [ $(ghc --numeric-version) != ${GHC} ]; then
-            travis_retry sudo apt-get install -y ghc-${GHC}
-            export PATH=/opt/ghc/${GHC}/bin:${PATH}
-        fi
-    - |
-        if [ ${CABAL} ]; then
-            travis_retry sudo apt-get install -y cabal-install-${CABAL}
-            export PATH=/opt/cabal/${CABAL}/bin:${PATH}
-        fi
-
-    # Maybe install the CUDA library
-    - |
-        if [ ${CUDA} ]; then
-
-            # If we want to build c2hs from source, ghc-7.8 and later will require newer
-            # versions of happy and alex
-            if [ ${GHC%.*} != 7.6 ]; then
-                travis_retry sudo apt-get install -y alex-${ALEX} happy-${HAPPY}
-                export PATH=/opt/alex/${ALEX}/bin:/opt/happy/${HAPPY}/bin:${PATH}
-            fi
-            cabal install c2hs
-
-            # Need to install a newer version of the Cabal library in order to run the
-            # Setup.hs script
-            cabal install Cabal --constraint="Cabal >= 1.22"
-
-            echo "Installing CUDA library"
-            travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
-            travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
-            travis_retry sudo apt-get update -qq
-            export CUDA_APT=${CUDA%-*}
-            export CUDA_APT=${CUDA_APT/./-}
-            travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT}
-            travis_retry sudo apt-get clean
-            export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
-            export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
-            export PATH=${CUDA_HOME}/bin:${PATH}
-        else
-            export MODE=-f-cuda
-        fi
+ - unset CC
+ - export PATH=/opt/ghc/$GHC/bin:/opt/cabal/$CABAL/bin:$PATH
 
 install:
-    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-    - cabal --version
-    - llc --version; true
-    - opt --version; true
-    - cabal install --only-dependencies --enable-tests ${MODE} . deps/*
-    - cabal install ${MODE} deps/*
+ - cabal --version
+ - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+ - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
+   then
+     zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
+          $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
+   fi
+ - travis_retry cabal update -v
+ - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
+ - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
+ - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt
 
+# check whether current requested install-plan matches cached package-db snapshot
+ - if diff -u installplan.txt $HOME/.cabal-snapshot/installplan.txt;
+   then
+     echo "cabal build-cache HIT";
+     rm -rfv .ghc;
+     cp -a $HOME/.cabal-snapshot/ghc $HOME/.ghc;
+     cp -a $HOME/.cabal-snapshot/lib $HOME/.cabal-snapshot/share $HOME/.cabal-snapshot/bin $HOME/.cabal/;
+   else
+     echo "cabal build-cache MISS";
+     rm -rf $HOME/.cabal-snapshot;
+     mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
+     cabal install --only-dependencies --enable-tests --enable-benchmarks;
+   fi
+
+# snapshot package-db on cache miss
+ - if [ ! -d $HOME/.cabal-snapshot ];
+   then
+      echo "snapshotting package-db to build-cache";
+      mkdir $HOME/.cabal-snapshot;
+      cp -a $HOME/.ghc $HOME/.cabal-snapshot/ghc;
+      cp -a $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin installplan.txt $HOME/.cabal-snapshot/;
+   fi
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-    # Check the build
-    - cabal configure -v2 -flib-Werror ${MODE}
-    - cabal build
-    - cabal haddock
-#    - cabal test --show-details=always
+ - if [ -f configure.ac ]; then autoreconf -i; fi
+ - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal build   # this builds all libraries and executables (including tests/benchmarks)
+ # - cabal test
+ # - cabal check
+ - cabal sdist   # tests that a source-distribution can be generated
 
-    # Check the source distribution can be generated, built, and installed
-    - cabal sdist
-    - |
-        export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')
-        cd dist
-        if [ -f "$SRC_TGZ" ]; then
-            travis_wait cabal install --force-reinstalls ${MODE} ${SRC_TGZ} || exit 1
-        else
-            echo "'$SRC_TGZ': not found"
-            exit 1
-        fi
+# Check that the resulting source distribution can be built & installed.
+# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
+# `cabal install --force-reinstalls dist/*-*.tar.gz`
+ - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
+   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")
 
-after_failure:
-    - dmesg
-    - ls -R /usr/local/cuda*
-
+# EOF
